/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ms3.landing.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Announcement service. Represents a row in the &quot;landing_Announcement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ms3.landing.service.model.impl.AnnouncementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ms3.landing.service.model.impl.AnnouncementImpl}.
 * </p>
 *
 * @author John
 * @see Announcement
 * @see com.ms3.landing.service.model.impl.AnnouncementImpl
 * @see com.ms3.landing.service.model.impl.AnnouncementModelImpl
 * @generated
 */
public interface AnnouncementModel extends BaseModel<Announcement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a announcement model instance should use the {@link Announcement} interface instead.
	 */

	/**
	 * Returns the primary key of this announcement.
	 *
	 * @return the primary key of this announcement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this announcement.
	 *
	 * @param primaryKey the primary key of this announcement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the i d of this announcement.
	 *
	 * @return the i d of this announcement
	 */
	public long getID();

	/**
	 * Sets the i d of this announcement.
	 *
	 * @param ID the i d of this announcement
	 */
	public void setID(long ID);

	/**
	 * Returns the title of this announcement.
	 *
	 * @return the title of this announcement
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this announcement.
	 *
	 * @param Title the title of this announcement
	 */
	public void setTitle(String Title);

	/**
	 * Returns the content of this announcement.
	 *
	 * @return the content of this announcement
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this announcement.
	 *
	 * @param Content the content of this announcement
	 */
	public void setContent(String Content);

	/**
	 * Returns the set date of this announcement.
	 *
	 * @return the set date of this announcement
	 */
	public Date getSetDate();

	/**
	 * Sets the set date of this announcement.
	 *
	 * @param SetDate the set date of this announcement
	 */
	public void setSetDate(Date SetDate);

	/**
	 * Returns the author of this announcement.
	 *
	 * @return the author of this announcement
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this announcement.
	 *
	 * @param Author the author of this announcement
	 */
	public void setAuthor(String Author);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Announcement announcement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Announcement> toCacheModel();

	@Override
	public Announcement toEscapedModel();

	@Override
	public Announcement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}